version: "3"

services:
  backend:
    container_name: game-star-wars
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "${PORT}:${PORT}"
    env_file:
     - .env
